config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'dashboard/application#index'
  mount ActionCable.server => '/cable'
  apipie
  devise_for :users, only: []
  devise_for :admins, path: 'dashboard', only: :sessions

  authenticate :admin, lambda { |u| u.try(:admin?) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :dashboard do
    resources :payments
    resources :users do
      member do
        post :notifications_and_messages
        post :message_push_notifications
        post :notification_push_notifications
      end
    end
    resources :parking_zones
    resources :kiosks
    resources :manufacturers
    resources :agencies
    resources :locations
    resources :cameras do
      get :vmarkup, on: :member
    end
    resources :roles do
      resources :permissions, module: :roles do
        resources :attributes, module: :permissions
      end
    end

    namespace :ai do
      resources :logs
      resources :tokens
    end

    namespace :paper_trail do
      resources :version
    end

    namespace :ksk do
      resources :tokens do
        collection do
          get :seed
        end
      end
    end

    scope path: :ksk do
      resources :parking_lots do
        get :outline, on: :member
        member do
          post :reset_sessions
        end
      end
      resources :vehicles do
        member do
          post :reset_sessions
        end
        collection do
          get :search
        end
      end
      resources :parking_slots do
        member do
          post :reset_sessions
        end
      end
      resources :parking_sessions do
        member do
          post :reset_session
        end
        collection do
          get :search
        end
      end
    end

    namespace :parking do
      resources :settings
    end

    root to: "parking_sessions#index"
    get 'env', to: 'application#env'
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :dropdowns, only: [:show]
      resources :pages, only: [:show]

      ['cardconnect_merchant_id_test', 'cardconnect_merchant_id_production'].each do |id|
        get "env/#{id}", to: "env##{id}"
      end

      namespace :ksk do
        resources :parking_lots do
          member do
            get :parking_zones
            get :kiosks
          end
        end
        resources :parking_zones do
          member do
            get :parking_slots
          end
        end
        resources :parking_sessions, only: [:index, :show] do
          member do
            put :confirm
            get :payment
          end
        end
        resources :parking_slots
        resources :vehicles
        resources :kiosks
      end
      namespace :ai do
        resources :parking_sessions, only: [:index] do
          collection do
            post :car_entrance
            post :car_parked
            post :car_left
            post :car_exit
            post :violation_commited
          end
        end
      end
      resources :users, only: [] do

        collection do
          get :check_credit_card
          post :check_reset_password_token
          post :sign_in
          post :sign_up
          post :send_reset_password_instructions
          post :send_confirmation_instructions
          put :confirm
          put :update_password
          put :reset_password
          get :me
          post :check_password
          put :update_settings
          post :push_notification_token
        end
      end
      resources :vehicles, only: [:create, :destroy, :index] do
        collection do
          get :verify
        end
      end
      resources :parking_sessions, only: [:index, :show] do
        collection do
          get :current
          get :recent
        end

        member do
          get :payment
          put :confirm
          post :pay
        end
      end
      resources :messages, only: [:index, :show] do
        collection do
          put :read, action: :mark_read
          get :unread
          get :types
        end
      end
      resources :notifications, only: [:update, :index] do
        collection do
          get :read
          put :read, action: :mark_read
          get :unread
          get :types
        end
      end
      resources :parking_lots, only: [:index, :show]
      resources :disputes, only: [:create]
      resources :alerts, only: [:index] do
        member do
          get :resolve
        end
      end
      resources :payments, only: [:index]
    end
    namespace :dashboard do
      post 'auth/sign_in', to: 'auth#sign_in'
      post 'auth/send_reset_password_instructions', to: 'auth#send_reset_password_instructions'
      post 'auth/check_reset_password_token', to: 'auth#check_reset_password_token'
      put 'auth/reset_password', to: 'auth#reset_password'
      post 'auth/push_notification_token', to: 'auth#push_notification_token'
      resources :dropdowns, only: [:show]
      resources :reports, only: [:index, :show]
      resources :statistics, only: [:index]
      resources :admins, only: [:create, :update, :index, :show] do
        collection do
          put :me, to: "admins#update_me"
          get :me
          get :search
          post :check_password
        end
      end

      resources :parking_sessions, only: [:index, :show] do
        collection do
          get :report
        end
      end
      resources :parking_lots, only: [:create, :update, :index, :show] do
        resources :parking_slots, only: [:index]
        resources :parking_plans, only: [:create, :destroy, :update]
      end
      resources :parking_rules, path: :parking_rules, only: [:index], controller: 'parking/rules' do
        collection do
          put :update
          patch :update
        end
      end

      resources :agencies, only: [:create, :update, :index, :show] do
        get :search, on: :collection
      end

      namespace :parking do
        resources :tickets, only: [:index, :update, :show]
        resources :vehicle_rules, path: '/lots/:lot_id/vehicle_rules', only: [:create, :index, :update] do
          collection do
            put :archive
          end
        end
      end

      resources :disputes, only: [:index, :show]
      resources :cameras, only: [:index, :show, :create, :update]
      resources :roles, only: [:index]
    end
  end

  resources :parking_lots do
    member do
      get :parking_zones
      get :kiosks
    end
  end
  resources :parking_zones do
    member do
      get :parking_slots
    end
  end
  resources :parking_slots
  resources :vehicles
  resources :kiosks
  resources :parking_sessions
  resources :payment_transactions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/api/dashboard/admins_controller.rb
module Api
  module Dashboard
    class AdminsController < ::Api::Dashboard::ApplicationController
      wrap_parameters :admin, include: Admin.attribute_names + [:password]

      api :GET, '/api/dashboard/admins', 'Fetch paginated user list'
      header :Authorization, 'Auth token', required: true
      param :per_page, Integer, 'Items per page count, default is 10. Check response headers for total count (key: X-Total)', required: false
      param :page, Integer, 'Items page number', required: false
      param :role_id, Integer, required: false
      param :status, Admin.statuses.keys, required: false
      param :query, String, 'Query (can be substring of username, email or name)', required: false

      def index
        scope = paginate Api::Dashboard::AdminsQuery.call(params.merge(user: current_user))
        respond_with scope, each_serializer: ::Api::Dashboard::UserSerializer
      end

      api :GET, '/api/dashboard/admins/search', 'Search for users'
      header :Authorization, 'Auth token'
      param :per_page, Integer, 'Items per page count, default is 10. Check response headers for total count (key: X-Total)'
      param :page, Integer, 'Items page number'
      param :role_id, Integer
      param :role_names, String, 'Search by role names'
      param :status, Admin.statuses.keys
      param :subject_type, [Agency.name, ParkingLot.name]
      param :subject_id, Integer, 'agency or parking lot id'
      param :query, String, 'Query (can be substring of username, email or name)'

      def search
        scope = paginate Api::Dashboard::AdminsSearchQuery.call(params.merge(user: current_user))
        respond_with scope, each_serializer: ::Api::Dashboard::UserSerializer
      end

      api :POST, '/api/dashboard/admins', 'Create new dashboard user'
      header :Authorization, 'Auth token', required: true
      param :admin, Hash do
        param :email, String, required: true
        param :status, Admin.statuses.keys, required: true
        param :username, String, required: true
        param :name, String, required: true
        param :phone, String, required: false
        param :avatar, String, 'File or base64', required: true
        param :role_id, Integer, required: true
      end

      def create
        payload = params.fetch(:admin, {}).merge(current_user: current_user)
        return unless role = set_role(payload[:role_id])
        authorize! role, with: AdminPolicy
        result = ::Admins::Create.run(payload)
        respond_with result, serializer: ::Api::Dashboard::DetailedUserSerializer
      end

      api :GET, '/api/dashboard/admins/me', 'Get current user'
      header :Authorization, 'Auth token', required: true

      def me
        respond_with current_user, serializer: ::Api::Dashboard::DetailedUserSerializer
      end

      api :PUT, '/api/dashboard/admins/me', 'Update current user dashboard'
      header :Authorization, 'Auth token', required: true
      param :admin, Hash do
        param :email, String, required: false
        param :username, String, required: false
        param :name, String, required: false
        param :phone, String, required: false
        param :avatar, String, 'File or base64', required: false
        param :delete_avatar, [true, false], 'Indicate if the avatar image should be destroyed', required: false
        param :old_password, String, "Should be blank, if user don't want to change his current password", required: false
        param :password, String, "Should be blank, if user don't want to change it", required: false
      end

      def update_me
        payload = params.fetch(:admin, {}).merge(current_user: current_user)
        result = ::Admins::UpdateCurrentUser.run(payload)
        respond_with result, serializer: ::Api::Dashboard::DetailedUserSerializer
      end

      api :PUT, '/api/dashboard/admins/:id', 'Update dashboard user'
      param :id, Integer, 'User id', required: true
      header :Authorization, 'Auth token', required: true
      param :admin, Hash do
        param :email, String, required: false
        param :status, Admin.statuses.keys, required: false
        param :username, String, required: false
        param :name, String, required: false
        param :phone, String, required: false
        param :avatar, String, 'File or base64', required: false
        param :role_id, Integer, required: false
        param :delete_avatar, [true, false], 'Indicate if the avatar image should be destroyed', required: false
        param :password, String, "Should be blank, if user don't want to change it", required: false
      end

      def update
        user = Admin.find(params[:id])
        payload = params.fetch(:admin, {}).merge(current_user: current_user, user: user)
        return unless role = set_role(payload[:role_id])
        authorize! role, with: AdminPolicy, to: :create?
        authorize! user
        result = ::Admins::Update.run(payload)
        respond_with result, serializer: ::Api::Dashboard::DetailedUserSerializer
      end

      api :GET, "/api/dashboard/admins/:id", 'Get user by ID'
      param :id, Integer, 'User id', required: true
      header :Authorization, 'Auth token', required: true

      def show
        user = Admin.find(params[:id])
        authorize! user
        respond_with user, serializer: ::Api::Dashboard::DetailedUserSerializer
      end

      api :POST, '/api/dashboard/admins/check_password', 'Check current admin password'
      param :admin, Hash do
        param :password, String, 'Current admin password', required: true
      end
      header :Authorization, 'Auth token', required: true

      def check_password
        result = current_user.valid_password?(params.dig(:admin, :password))
        render json: { result: result }
      end

      private

      def per_page
        params[:per_page] || 20
      end

      def set_role(id)
        role = Role.find_by(id: id)
        role_not_found! unless role.present?
        role
      end
    end
  end
end

app/controllers/api/dashboard/application_controller.rb
module Api
  module Dashboard
    class ApplicationController < ::Api::ApplicationController
      before_action :authenticate_admin!
      before_action :set_paper_trail_whodunnit
      before_action :store_tracker_id

      def authenticate_admin!
        return unauthorized! unless current_user
        return account_suspended! unless current_user.active?
      end

      def current_user
        @current_user ||= Authorizer.authorize_by_token(request.headers['Authorization'], Admin)
      end

      private

      def store_tracker_id
        return if current_user.nil? || request.headers['psad-tracker-id'].nil?
        return if current_user.trackers.include?(request.headers['psad-tracker-id'])
        @current_user.trackers.push(request.headers['psad-tracker-id'])
        @current_user.save
      end
    end
  end
end

app/controllers/api/dashboard/auth_controller.rb
module Api
  module Dashboard
    class AuthController < ::Api::Dashboard::ApplicationController
      skip_before_action :authenticate_admin!, only: [:send_reset_password_instructions, :sign_in, :reset_password, :check_reset_password_token]
      wrap_parameters :admin

      api :POST, '/api/dashboard/auth/sign_in', 'Admin sign in'
      param :admin, Hash do
        param :username, String, 'Email or username', required: true
        param :password, String, required: true
      end

      def sign_in
        result = ::Admins::SignIn.run(params.fetch(:admin, {}))
        respond_with result
      end

      api :POST, '/api/dashboard/auth/send_reset_password_instructions', 'Send reset password instructions'
      param :admin, Hash do
        param :username, String, required: true
      end

      def send_reset_password_instructions
        payload = params.fetch(:admin, {})
        result = ::Admins::ResetPasswordMail.run(payload)
        respond_with result
      end

      api :PUT, '/api/dashboard/auth/reset_password', 'Reset admin password with token from mail'
      param :admin, Hash do
        param :reset_password_token, String, 'Reset password token', required: true
        param :password, String, 'New password', required: true
      end

      def reset_password
        payload = params.require(:admin).permit(:password, :reset_password_token).merge(klass: Admin)
        result = ::Users::ResetPassword.run(payload)
        respond_with result
      end

      api :POST, '/api/dashboard/auth/check_reset_password_token', 'Reset admin password with token from mail'
      param :token, String, 'Reset password token', required: true

      def check_reset_password_token
        render json: {
          validToken: Admin.with_reset_password_token(params[:token]).present?
        }, status: 200
      end

      api :POST, '/api/dashboard/auth/push_notification_token', 'Set push notification token'
      header :Authorization, 'Auth token', required: true
      param :admin, Hash do
        param :push_notification_token, String, 'Push Notification token returned by firebase', required: true
      end

      def push_notification_token
        return head(:bad_request) unless params.dig(:admin, :push_notification_token)
        id, auth_token = request.headers['Authorization'].split(':')[0], request.headers['Authorization'].split(':')[1]
        admin_token = current_user.find_by_token(auth_token)
        admin_token.update!(admin_push_notification_token: Admin::PushNotificationToken.create(value: params[:admin][:push_notification_token]))
        head :created
      end

    end
  end
end

app/controllers/api/dashboard/disputes_controller.rb
module Api
  module Dashboard
    class DisputesController < ApplicationController
      api :GET, '/api/dashboard/disputes', 'Disputes list'
      header :Authorization, 'Auth token from users#sign_in', required: true
      param :status, String, 'Status of dispute'
      param :parking_lot_id, Integer, 'Parking lot id'
      param :admin_id, Integer, 'Admin id (Dispute resolver)'

      def index
        scope = DisputesIndexQuery.call(params.merge(user: current_user))
        respond_with paginate(scope), each_serializer: DisputeSerializer
      end

      api :GET, '/api/dashboard/disputes/:id', 'Dispute details'
      header :Authorization, 'Auth token from users#sign_in', required: true

      def show
        dispute = Dispute.find(params[:id])
        authorize! dispute
        respond_with dispute, serializer: DisputeShowSerializer
      end
    end
  end
end

app/views/dashboard/parking_sessions/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

app/views/dashboard/parking_sessions/edit.html.erb
<%#
# Edit

This view is the template for the edit page.

It displays a header, and renders the `_form` partial to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { t("administrate.actions.edit_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.show_resource", name: page.page_title),
      [namespace, page.resource],
      class: "button",
    ) if valid_action?(:show) && show_action?(:show, page.resource) %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/dashboard/parking_sessions/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<%= content_for :stylesheet do %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<% end %>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <%= form_for :search, url: search_dashboard_parking_sessions_path, method: :get, html: { class: 'mr-1' } do |f| %>
    <div class="form-row align-items-center">
      <div class="col-auto my-1">
        <%= f.text_field :uuid, placeholder: "UUID", class: 'form-control' %>
      </div>
      <div class="col-auto my-1">
        <%= f.select :lot_id, ParkingLot.order("id").pluck(:name, :id), {}, class: 'form-control' %>
      </div>
      <div class="col-auto my-1">
        <%= f.submit :filter %>
      </div>
    </div>
  <% end %>


</header>

<section class="main-content__body main-content__body--flush">
  <%= render(
          "collection",
          collection_presenter: page,
          collection_field_name: resource_name,
          page: page,
          resources: resources,
          table_title: "page-title"
      ) %>

  <%= paginate resources %>
</section>

app/views/dashboard/parking_sessions/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { t("administrate.actions.show_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.edit_resource", name: page.page_title),
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action?(:edit) && show_action?(:edit, page.resource) %>
    <%= link_to( 'Finish Session', [:reset_session, namespace , page.resource], method: :post, class: "button" ) %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: attribute.name.titleize,
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
          ><%= render_field attribute, page: page %></dd>
    <% end %>
  </dl>
</section>